### ISSUE TITLE
Search based on McM tags

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pmp#73]
mcm Tags
( see attached screenshot )
are used to identify groups of requests sharing a property or purpose.

==> Can we have pmp capable of searching request
 based on Tags 
( the same way as we currently search for campaign name, process string, floews et ) ?

@klute and I think that
Tags could be used much more extensively to mark, 
e.g. samples needed for a specific analysis
( this policy is to be discussed in the context of mccm procedures review, not here).

<img width="1341" alt="screen shot 2018-05-08 at 14 06 15" src="https://user-images.githubusercontent.com/4729828/39756436-ee144cc8-52c9-11e8-82f1-61e315e3e710.png">

**Comment by franzoni** [comment]
I mean the same capability, for pmp.

**Comment by franzoni** [comment]
Thanks a lot for making this work!

Looking at a concrete example, https://cms-pdmv.cern.ch/pmp/historical?r=Fall17P1A , 

why the request which are not complete don't appear at the bottom of the view ( as they do, when searching for instance by campaign ) ?

**Comment by franzoni** [comment]
@justinasr 
other than this little fix I ask, isn't basically this issue clos-able ?

**Comment by justinasr** [comment]
Good catch, there was a bug that when searching by tags, submitted requests did not appear. However, for this exact case with Fall17P1A, it's empty because none of them have output datasets:

https://cms-pdmv.cern.ch/mcm/requests?tags=Fall17P1A&page=0&status=submitted&shown=536873037&limit=100

pMp searches for output dataset in a request.

The bug that I mentioned in the beginning is now fixed and if you use other tag, for example HWW, it shows submitted requests:

https://cms-pdmv.cern.ch/pmp/historical?r=HWW
