### ISSUE TITLE
dowloading pdf requires certificate

### ISSUE THREAD

**Issue by franzoni** [cms-PdmV/pMp#91]
Hello @justinasr  and PdmV gurus,

when trying to get a Pdf, all is well when I push the button, a separate window appears with the pdf itself. When trying do download it, I get no Pdf and a small error message in the browser tab which would report the target fole location saying "Failed - Bad certificate" (see image).

![Screenshot 2020-01-08 at 11 00 51](https://user-images.githubusercontent.com/4729828/71969040-38103400-3206-11ea-87a6-baec4d827057.png)

At the command line, the same error is reproduced.
I manage at the command line to the the Pdf if I force no check certificate.

wget   https://cms-pdmv.cern.ch/pmp/static/tmp/pmp_2020-01-08_10-17-58-360013.pdf  --no-check-certificate

I doubt this is intended, perhaps some unneeded credentials checks to be shaved off ?

Cheers and happy 2020!
G.

**Comment by justinasr** [comment]
Hello,

Strange, the only authorization that pMp requires is SSO. All requests go through AlCa's proxy. Since it works with `--no-check-certificate`, I would assume that this is issue of https certificate being issued by CERN Grid CA which is "certificate issuer is unknown, the certificate is self-signed, or the server is not sending the correct intermediate certificates".

I would suggest trying to add CERN Grid CA to your browser trusted certificate authorities list (https://cafiles.cern.ch/cafiles/certificates/Grid.aspx).

Justinas R.
