### ISSUE TITLE
wrong number of events expected

### ISSUE THREAD

**Issue by ameyer-cern** [cms-PdmV/pmp#95]
Hello Justinas,

On this page: https://cms-pdmv.cern.ch/pmp/historical?r=RunIIAutumn18NanoAODv7,RunIIFall17NanoAODv7,RunIISummer16NanoAODv7&priority=112000,112001&sortSubmittedOn=expected
I think the following three requests for which the displayed number of expected events is wrong. 

E.g., for one of them, the link here shows 4M expected, but it seems there are only 2.4M events: 
https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_TOP-RunIIAutumn18DRPremix-00347

![Screenshot 2020-05-17 at 18 25 58](https://user-images.githubusercontent.com/52288336/82154114-12f29880-986c-11ea-96ef-2065cfc80b8d.jpg)

Andreas

**Comment by justinasr** [comment]
Hello,
pMp takes number of expected events from McM. McM has this flaw that number of expected events are not updated frequently, as far as I can see only when request is created or chained request flows to that request. Number of expected events is set to number of completed events of the previous request. In this case NanoAOD requests were created or flowed to when MiniAOD (or I think even GS, because DR + Mini + Nano were submitted together) had only 300/300/11200 requests done and never updated.

I believe McM can use expected events from ReqMgr2 to get the accurate number, I'll see if that would work.

Justinas R.

**Comment by justinasr** [comment]
Hello,
I updated McM code, so it would also update number of expected events and triggered manual update of these three requests and pMp update, so now historical plot looks nicer.
All requests that are currently submitted will get (if needed) expected events update automatically at some point in near future (whenever they are updated in Stats).
All requests that are already done and have incorrect number of expected events will have to be explicitly triggered to update.

I am thinking of a slowly (to not increase load) running script that could go through all done requests in McM and update (if needed) number total events.

Justinas R.
